version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD='Isidro123$'
      - MYSQL_DATABASE='db-isidro'
      - MYSQL_USER='isidro'
      - MYSQL_PASSWORD='Isidro123$'
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql
