version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Isidro123$
    volumes:
      - db_data:/var/lib/mysql
      - ./backup:/backup
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
  backup:
    image: busybox
    volumes:
      - db_data:/db_data
      - ./backup:/backup
    command: cp -r /db_data /backup/$(date +%Y%m%d%H%M%S)
    depends_on:
      - db
volumes:
  db_data:
